file= open("pini.txt","w")
file.write("this is file management uing python")
file.close()
print("file written succesfully")
print("*************************")
file=open("pini.txt","r")
print(file.read())
file.close()
#print("file readed")
print("*******")
file=open("pini.txt",'a')
file.write("this file is now appeneded")
file.close()
#print("file appended successfully)
file=open("pini.txt","r")
print(file.read())
file.close()
print("*******")
file=open("kr.txt","w+")
file.write("hello world good morning guys")
print(file.read())
print("**************")
print("current file position",file.tell())
print(file.seek(0))
print(file.read())
